DataAccessRegistry:
  Name: "default"
  ReadOnlyConnection: "Data Source=localhost;Initial Catalog=PedidosDb;Trusted_Connection=True; Integrated Security=True; TrustServerCertificate=True"
  TransactionalConnection: "Data Source=localhost;Initial Catalog=PedidosDb;Trusted_Connection=True; Integrated Security=True; TrustServerCertificate=True"
  ProviderName: System.Data.SqlClient

AMQStreams:
  BootstrapServer: "SSL://cluster-kafka-bootstrap-amq-streams-test.apps.ocptest.andreani.com.ar:443"
  SchemaUrl: "http://apicurioregistry.apps.ocptest.andreani.com.ar/apis/ccompat/v6"
  Protocol: Ssl
  AutoOffsetReset: Earliest
  AutoRegisterSchemas: true
  MaxRetry: 3